import type { HistoricalFigure } from "./types";

export const figures: HistoricalFigure[] = [
  // ── Scientists ────────────────────────────────────────────
  {
    id: 1,
    name: "Marie Curie",
    category: "Scientist",
    birthYear: 1867,
    deathYear: 1934,
    nationality: "Polish-French",
    knownFor: "Radioactivity research; first person to win Nobel Prizes in two different sciences",
    emoji: "🧪",
  },
  {
    id: 2,
    name: "Isaac Newton",
    category: "Scientist",
    birthYear: 1643,
    deathYear: 1727,
    nationality: "English",
    knownFor: "Laws of motion and universal gravitation; co-invented calculus",
    emoji: "🍎",
  },
  {
    id: 3,
    name: "Ada Lovelace",
    category: "Scientist",
    birthYear: 1815,
    deathYear: 1852,
    nationality: "English",
    knownFor: "Wrote the first algorithm intended for a computing machine; pioneer of computer science",
    emoji: "💻",
  },

  // ── Leaders ───────────────────────────────────────────────
  {
    id: 4,
    name: "Julius Caesar",
    category: "Leader",
    birthYear: -100,
    deathYear: -44,
    nationality: "Roman",
    knownFor: "Conquered Gaul, reformed the Roman calendar, and transformed the Roman Republic",
    emoji: "⚔️",
  },
  {
    id: 5,
    name: "Cleopatra VII",
    category: "Leader",
    birthYear: -69,
    deathYear: -30,
    nationality: "Egyptian",
    knownFor: "Last active ruler of the Ptolemaic Kingdom; forged alliances with Julius Caesar and Mark Antony",
    emoji: "👑",
  },
  {
    id: 6,
    name: "Napoleon Bonaparte",
    category: "Leader",
    birthYear: 1769,
    deathYear: 1821,
    nationality: "French",
    knownFor: "Conquered much of Europe; reformed law with the Napoleonic Code",
    emoji: "🎖️",
  },

  // ── Artists ───────────────────────────────────────────────
  {
    id: 7,
    name: "Leonardo da Vinci",
    category: "Artist",
    birthYear: 1452,
    deathYear: 1519,
    nationality: "Italian",
    knownFor: "Painted the Mona Lisa and The Last Supper; designed flying machines and anatomical studies",
    emoji: "🎨",
  },
  {
    id: 8,
    name: "Frida Kahlo",
    category: "Artist",
    birthYear: 1907,
    deathYear: 1954,
    nationality: "Mexican",
    knownFor: "Surrealist self-portraits exploring identity, pain, and Mexican cultural heritage",
    emoji: "🌺",
  },
  {
    id: 9,
    name: "Wolfgang Mozart",
    category: "Artist",
    birthYear: 1756,
    deathYear: 1791,
    nationality: "Austrian",
    knownFor: "Composed over 800 works including symphonies, operas, and chamber music",
    emoji: "🎵",
  },

  // ── Philosophers ──────────────────────────────────────────
  {
    id: 10,
    name: "Aristotle",
    category: "Philosopher",
    birthYear: -384,
    deathYear: -322,
    nationality: "Greek",
    knownFor: "Founded formal logic; wrote foundational texts on physics, biology, ethics, and politics",
    emoji: "📜",
  },
  {
    id: 11,
    name: "Immanuel Kant",
    category: "Philosopher",
    birthYear: 1724,
    deathYear: 1804,
    nationality: "German",
    knownFor: "Critique of Pure Reason; developed the categorical imperative in moral philosophy",
    emoji: "🔭",
  },
  {
    id: 12,
    name: "Confucius",
    category: "Philosopher",
    birthYear: -551,
    deathYear: -479,
    nationality: "Chinese",
    knownFor: "Teachings on ethics, family loyalty, and social harmony that founded Confucianism",
    emoji: "☯️",
  },
];
